export type ThemeMode = "light" | "dark";

export const THEME_STORAGE_KEY = "learningopk-design-system-theme";

export const themeTokens = {
  colors: {
    light: {
      background: "#f8fafc",
      foreground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      primary: "#7ac943",
      primaryForeground: "#ffffff",
      primaryHover: "#68b036",
      secondary: "#f1f5f9",
      secondaryForeground: "#0f172a",
      muted: "#e2e8f0",
      mutedForeground: "#64748b",
      accent: "#f1f5f9",
      accentForeground: "#0f172a",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      success: "#10b981",
      successForeground: "#ffffff",
      warning: "#f59e0b",
      warningForeground: "#ffffff",
      border: "#e2e8f0",
      input: "#cbd5e1",
      ring: "#7ac943",
    },
    dark: {
      background: "#0f172a",
      foreground: "#f8fafc",
      card: "#1e293b",
      cardForeground: "#f8fafc",
      popover: "#1e293b",
      popoverForeground: "#f8fafc",
      primary: "#7ac943",
      primaryForeground: "#0f172a",
      primaryHover: "#8fd654",
      secondary: "#1e293b",
      secondaryForeground: "#f8fafc",
      muted: "#334155",
      mutedForeground: "#94a3b8",
      accent: "#1e293b",
      accentForeground: "#f8fafc",
      destructive: "#f87171",
      destructiveForeground: "#0f172a",
      success: "#34d399",
      successForeground: "#0f172a",
      warning: "#fbbf24",
      warningForeground: "#0f172a",
      border: "#334155",
      input: "#475569",
      ring: "#7ac943",
    },
  },
  spacing: {
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
    16: "4rem",
  },
  typography: {
    fontFamily: {
      heading: '"Montserrat", sans-serif',
      body: '"Plus Jakarta Sans", sans-serif',
      mono: '"JetBrains Mono", monospace',
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
    },
    fontWeight: {
      normal: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
    },
    lineHeight: {
      tight: "1.25",
      normal: "1.5",
      relaxed: "1.75",
    },
  },
  shadows: {
    sm: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
    md: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
    lg: "0 10px 15px -3px rgb(0 0 0 / 0.1)",
  },
  animation: {
    duration: {
      fast: "150ms",
      normal: "200ms",
      slow: "300ms",
    },
  },
};

export type ThemeTokens = typeof themeTokens;

export const getCssVariables = (mode: ThemeMode) => {
  const colors = themeTokens.colors[mode];

  return {
    "--background": colors.background,
    "--foreground": colors.foreground,
    "--card": colors.card,
    "--card-foreground": colors.cardForeground,
    "--popover": colors.popover,
    "--popover-foreground": colors.popoverForeground,
    "--primary": colors.primary,
    "--primary-foreground": colors.primaryForeground,
    "--primary-hover": colors.primaryHover,
    "--primary-light": mode === "light" ? "rgba(122, 201, 67, 0.2)" : "rgba(122, 201, 67, 0.3)",
    "--secondary": colors.secondary,
    "--secondary-foreground": colors.secondaryForeground,
    "--muted": colors.muted,
    "--muted-foreground": colors.mutedForeground,
    "--accent": colors.accent,
    "--accent-foreground": colors.accentForeground,
    "--destructive": colors.destructive,
    "--destructive-foreground": colors.destructiveForeground,
    "--success": colors.success,
    "--success-foreground": colors.successForeground,
    "--warning": colors.warning,
    "--warning-foreground": colors.warningForeground,
    "--border": colors.border,
    "--input": colors.input,
    "--ring": colors.ring,
    "--shadow-sm": themeTokens.shadows.sm,
    "--shadow-md": themeTokens.shadows.md,
    "--shadow-lg": themeTokens.shadows.lg,
    "--font-heading": themeTokens.typography.fontFamily.heading,
    "--font-body": themeTokens.typography.fontFamily.body,
    "--font-mono": themeTokens.typography.fontFamily.mono,
  };
};
