import {
  QUIZ_PASS_THRESHOLD_PERCENT,
  QUIZ_PASS_THRESHOLD_WEAK_AREA,
  QUIZ_NAVIGATOR_THRESHOLD,
  TIMER_INTERVAL_MS,
  TIMER_WARNING_SECONDS,
  TIMER_CRITICAL_SECONDS,
} from "@learningopk/shared/constants";

export {
  QUIZ_NAVIGATOR_THRESHOLD,
  TIMER_INTERVAL_MS,
  TIMER_WARNING_SECONDS,
  TIMER_CRITICAL_SECONDS,
  QUIZ_PASS_THRESHOLD_PERCENT as PERFORMANCE_EXCELLENT_THRESHOLD,
  QUIZ_PASS_THRESHOLD_WEAK_AREA as PERFORMANCE_PASS_THRESHOLD,
};
