export const QUIZ_NAVIGATOR_THRESHOLD = 20;
export const TIMER_INTERVAL_MS = 1000;
export const TIMER_WARNING_SECONDS = 300;
export const TIMER_CRITICAL_SECONDS = 60;
export const PERFORMANCE_EXCELLENT_THRESHOLD = 70;
export const PERFORMANCE_PASS_THRESHOLD = 50;
